add greets
Xenomorff/Testing pull request #3
Opened 2024-10-24 21:01 UTC by Xenomorff

создал функцию для вывода приветствия по имени

2024-10-26 09:02 UTC, Demonica22 requested changes

2024-10-26 09:02 UTC, Demonica22 commented on test.py
> +@app.get("/fibonacci/{n}")
Ты добавил сюда код из другой ветки, и вижу что отдельным коммитом. Это с какой-то определенной целью было сделано?

2024-10-26 09:02 UTC, Demonica22 commented on test.py
> +    if not isinstance(name, str):
А вот тут круто) красиво получилось

2024-10-28 18:40 UTC, Xenomorff commented on test.py
> +@app.get("/fibonacci/{n}")
нет, случайно, видимо. до конца не разобрался сначала, и так получилось.
кстати, по поводу isinstance(). если в данном случае использовать код:
if type(n) != 'int' and n < 0:
        raise TypeError('Введите натуральное число')

то тут пройдет тольк онатуральное число. но если использовать так:
if isinstance(n, int) and n < 0:
        raise TypeError('Введите натуральное число')

то тут, если ты решишь подать на вход True или False, то isinstance() 
определит их как 1 или 0, соответственно, пропустит дальше в исполнение программы.

2024-10-28 18:41 UTC, Xenomorff commented on test.py
> +    if not isinstance(name, str):
спасибо!

2024-11-10 16:02 UTC, Demonica22 approved these changes

2024-11-10 17:11 UTC, Demonica22 approved these changes

2024-11-10 17:12 UTC, merged